import copy

_author_ = 'int_soumen'
_date_ = "21-09-2018"

SLAVE_LIBRARY = {}
SERVER_JSON_CONF = {}

PING_REPLY = "OK FROM IOTP SERVER"

HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_SERVER_ERROR = 500


